site_name: Qubex
site_description: "Qubex: Qubit experiment framework"
repo_url: https://github.com/amachino/qubex
repo_name: amachino/qubex

docs_dir: docs
site_dir: site

theme:
  name: material
  icon:
    logo: material/book 
  font:
    text: Noto Sans
    code: Noto Sans Mono
  palette:
    - scheme: default
      primary: black
  features:
    - navigation.instant
    - navigation.footer
    - content.code.copy

plugins:
  - gh-admonitions
  - mkdocs-autoapi:
      autoapi_dir: src
      autoapi_root: api-reference
      autoapi_add_nav_entry: false
  - mkdocs-jupyter:
      execute: false
      include_source: true
      ignore_h1_titles: true
  - mkdocstrings:
      handlers:
        python:
          paths:
            - src
          options:
            docstring_style: numpy
            allow_inspection: false
            show_source: false
  - search

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

extra:
  generator: false

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Getting started:
      - Installation: user-guide/getting-started/installation.md
      - System configuration: user-guide/getting-started/system-configuration.md
      - Choose your entry point: user-guide/getting-started/choose-your-entry-point.md
  - Experiment:
      - Overview: user-guide/experiment/index.md
      - Quickstart: user-guide/getting-started/quickstart.md
      - Example workflows: user-guide/experiment/examples.md
      - Community-contributed workflows: user-guide/getting-started/contrib-workflows.md
  - Measurement:
      - Overview: user-guide/measurement/index.md
      - Example workflows: user-guide/measurement/examples.md
  - Simulator:
      - Overview: user-guide/simulator/index.md
      - Example workflows: user-guide/simulator/examples.md
  - Examples: examples/index.md
  - Contributing: CONTRIBUTING.md
  - Developer guide:
      - Overview: developer-guide/index.md
      - Development flow: developer-guide/development-flow.md
      - Experiment API delegation guidelines: developer-guide/experiment-api-delegation-guidelines.md
      - Document guidelines: developer-guide/document-guidelines.md
      - Docstring guidelines: developer-guide/docstring-guidelines.md
      - Dependency guidelines: developer-guide/dependency-guidelines.md
      - Test guidelines: developer-guide/test-guidelines.md
      - Contrib module guidelines: developer-guide/contrib-guidelines.md
      - Issue guidelines: developer-guide/issue-guidelines.md
      - Pull request guidelines: developer-guide/pull-request-guidelines.md
      - Commit message guidelines: developer-guide/commit-guidelines.md
  - API reference: api-reference/qubex/
