[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "qubex"
dynamic = ["version"]
requires-python = ">=3.9"
authors = [{ name = "Akinori Machino" }]
description = "Qubex: Qubit experiment framework"
readme = "README.md"
license = { file = "LICENSE" }
dependencies = [
    "cma ~= 4.0",
    "cvxopt ~= 1.3",
    "cvxpy ~= 1.6",
    "httpx ~= 0.0",
    "jax ~= 0.0",
    "jsonpickle ~= 3.0",
    "jupyter ~= 1.0",
    "kaleido == 0.2.1",
    "matplotlib ~= 3.0",
    "networkx ~= 3.0",
    "numpy ~= 1.0",
    "optax ~= 0.0",
    "pip == 24.0",
    "plotly ~= 5.23",
    "pydantic ~= 2.0",
    "pyserial ~= 3.5",
    "pyyaml ~= 6.0",
    "qctrl-visualizer ~= 8.0",
    "qutip ~= 5.0",
    "rich ~= 13.0",
    "scikit-learn ~= 1.0",
    "scipy ~= 1.0",
    "tqdm ~= 4.0",
]

[project.optional-dependencies]
backend = [
    "qubecalib @ git+https://github.com/qiqb-osaka/qube-calib.git@3.1.14",
]
dev = ["pyinstrument", "pytest", "pytest-cov", "ruff"]

[tool.setuptools.dynamic]
version = { attr = "qubex.version.get_version" }

[tool.setuptools.package-data]
qubex = ["py.typed", "clifford/**/*.json"]

[tool.pytest.ini_options]
addopts = "--import-mode=importlib"
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
]

[tool.coverage.run]
source = ["src/qubex"]
omit = [
    "*/tests/*",
    "*/test_*",
    "*/__pycache__/*",
    "*/third_party/*",
    "*/patches/*",
]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "if self.debug:",
    "if settings.DEBUG",
    "raise AssertionError",
    "raise NotImplementedError",
    "if 0:",
    "if __name__ == .__main__.:",
    "class .*\\bProtocol\\):",
    "@(abc\\.)?abstractmethod",
]
fail_under = 70
show_missing = true

[tool.ruff.lint]
ignore = ["E731", "E741"]
unfixable = ["F401"]
