# Example configuration for QuEL-3 boxes.
#
# Format
# ------
# <box_id>:
#   name: <unit_label>
#   type: <box_type>
#   address: <ip_address>  # optional for quel3
#   adapter: <adapter_id>  # optional for quel3

QT1:
  name: "quel3-02-a01"
  type: "quel3"
QT2:
  name: "QuEL-3 #2"
  type: "quel3"
QT3:
  name: "QuEL-3 #3"
  type: "quel3"
QT4:
  name: "QuEL-3 #4"
  type: "quel3"
QT5:
  name: "QuEL-3 #5"
  type: "quel3"
QT6:
  name: "QuEL-3 #6"
  type: "quel3"
QT7:
  name: "QuEL-3 #7"
  type: "quel3"
QT8:
  name: "QuEL-3 #8"
  type: "quel3"
