"""Default values for measurement configuration."""

from __future__ import annotations

from typing import Final

from qubex.pulse import RampType

DEFAULT_SHOTS: Final = 1024
DEFAULT_INTERVAL: Final = 150 * 1024  # ns

DEFAULT_READOUT_DURATION: Final = 384  # ns
DEFAULT_READOUT_RAMPTIME: Final = 32  # ns
DEFAULT_READOUT_PRE_MARGIN: Final = 32  # ns
DEFAULT_READOUT_POST_MARGIN: Final = 128  # ns
DEFAULT_READOUT_DRAG_COEFF: Final = 0.0
DEFAULT_READOUT_RAMP_TYPE: Final[RampType] = "RaisedCosine"

DEFAULT_ENABLE_DSP_DEMODULATION: Final = True
DEFAULT_ENABLE_DSP_SUM: Final = False
DEFAULT_ENABLE_DSP_CLASSIFICATION: Final = False

__all__ = [
    "DEFAULT_ENABLE_DSP_CLASSIFICATION",
    "DEFAULT_ENABLE_DSP_DEMODULATION",
    "DEFAULT_ENABLE_DSP_SUM",
    "DEFAULT_INTERVAL",
    "DEFAULT_READOUT_DRAG_COEFF",
    "DEFAULT_READOUT_DURATION",
    "DEFAULT_READOUT_POST_MARGIN",
    "DEFAULT_READOUT_PRE_MARGIN",
    "DEFAULT_READOUT_RAMPTIME",
    "DEFAULT_READOUT_RAMP_TYPE",
    "DEFAULT_SHOTS",
]
