64Q:
  resonator_frequency:
    # MUX00
    Q00: 10.290882
    Q01: 10.466604
    Q02: 10.348197
    Q03: 10.128692
    # MUX01
    Q04: null
    Q05: null
    Q06: null
    Q07: null
    # MUX02
    Q08: null
    Q09: null
    Q10: null
    Q11: null
    # MUX03
    Q12: null
    Q13: null
    Q14: null
    Q15: null
    # MUX04
    Q16: null
    Q17: null
    Q18: null
    Q19: null
    # MUX05
    Q20: null
    Q21: null
    Q22: null
    Q23: null
    # MUX06
    Q24: null
    Q25: null
    Q26: null
    Q27: null
    # MUX07
    Q28: null
    Q29: null
    Q30: null
    Q31: null
    # MUX08
    Q32: null
    Q33: null
    Q34: null
    Q35: null
    # MUX09
    Q36: null
    Q37: null
    Q38: null
    Q39: null
    # MUX10
    Q40: null
    Q41: null
    Q42: null
    Q43: null
    # MUX11
    Q44: null
    Q45: null
    Q46: null
    Q47: null
    # MUX12
    Q48: null
    Q49: null
    Q50: null
    Q51: null
    # MUX13
    Q52: null
    Q53: null
    Q54: null
    Q55: null
    # MUX14
    Q56: null
    Q57: null
    Q58: null
    Q59: null
    # MUX15
    Q60: null
    Q61: null
    Q62: null
    Q63: null

  qubit_frequency:
    # MUX00
    Q00: 6.832214
    Q01: 7.532409
    Q02: 7.557020
    Q03: 6.727803
    # MUX01
    Q04: null
    Q05: null
    Q06: null
    Q07: null
    # MUX02
    Q08: null
    Q09: null
    Q10: null
    Q11: null
    # MUX03
    Q12: null
    Q13: null
    Q14: null
    Q15: null
    # MUX04
    Q16: null
    Q17: null
    Q18: null
    Q19: null
    # MUX05
    Q20: null
    Q21: null
    Q22: null
    Q23: null
    # MUX06
    Q24: null
    Q25: null
    Q26: null
    Q27: null
    # MUX07
    Q28: null
    Q29: null
    Q30: null
    Q31: null
    # MUX08
    Q32: null
    Q33: null
    Q34: null
    Q35: null
    # MUX09
    Q36: null
    Q37: null
    Q38: null
    Q39: null
    # MUX10
    Q40: null
    Q41: null
    Q42: null
    Q43: null
    # MUX11
    Q44: null
    Q45: null
    Q46: null
    Q47: null
    # MUX12
    Q48: null
    Q49: null
    Q50: null
    Q51: null
    # MUX13
    Q52: null
    Q53: null
    Q54: null
    Q55: null
    # MUX14
    Q56: null
    Q57: null
    Q58: null
    Q59: null
    # MUX15
    Q60: null
    Q61: null
    Q62: null
    Q63: null

  anharmonicity:
    # MUX00
    Q00: -0.393715
    Q01: -0.505778
    Q02: -0.499147
    Q03: -0.385199
    # MUX01
    Q04: null
    Q05: null
    Q06: null
    Q07: null
    # MUX02
    Q08: null
    Q09: null
    Q10: null
    Q11: null
    # MUX03
    Q12: null
    Q13: null
    Q14: null
    Q15: null
    # MUX04
    Q16: null
    Q17: null
    Q18: null
    Q19: null
    # MUX05
    Q20: null
    Q21: null
    Q22: null
    Q23: null
    # MUX06
    Q24: null
    Q25: null
    Q26: null
    Q27: null
    # MUX07
    Q28: null
    Q29: null
    Q30: null
    Q31: null
    # MUX08
    Q32: null
    Q33: null
    Q34: null
    Q35: null
    # MUX09
    Q36: null
    Q37: null
    Q38: null
    Q39: null
    # MUX10
    Q40: null
    Q41: null
    Q42: null
    Q43: null
    # MUX11
    Q44: null
    Q45: null
    Q46: null
    Q47: null
    # MUX12
    Q48: null
    Q49: null
    Q50: null
    Q51: null
    # MUX13
    Q52: null
    Q53: null
    Q54: null
    Q55: null
    # MUX14
    Q56: null
    Q57: null
    Q58: null
    Q59: null
    # MUX15
    Q60: null
    Q61: null
    Q62: null
    Q63: null
