64Q:
  - mux: 0
    ctrl: [R21B-5, R21B-0, R21B-2, R21B-6]
    read_out: U15A-13
    read_in: U15A-12
    pump: U15A-11
  - mux: 1
    ctrl: [U15A-5, U15A-6, U15A-7, U15A-8]
    read_out: U15A-0
    read_in: U15A-1
    pump: U15A-2
  - mux: 2
    ctrl: [R21B-7, R21B-11, R21B-13, R21B-8]
    read_out: R20A-13
    read_in: R20A-12
  - mux: 4
    ctrl: [R19A-5, R19A-6, R19A-7, R19A-8]
    read_out: R19A-0
    read_in: R19A-1
  - mux: 5
    ctrl: [Q2A-2, Q2A-4, Q2A-9, Q2A-11]
    read_out: Q2A-1
    read_in: Q2A-0
  - mux: 6
    ctrl: [U10B-5, U10B-0, U10B-2, U10B-6]
    read_out: R19A-13
    read_in: R19A-12
  - mux: 7
    ctrl: [U10B-7, U10B-11, U10B-13, U10B-8]
    read_out: Q2A-8
    read_in: Q2A-7
  - mux: 8
    ctrl: [R26A-5, R26A-6, R26A-7, R26A-8]
    read_out: R26A-0
    read_in: R26A-1
  - mux: 9
    ctrl: [R31A-5, R31A-6, R31A-7, R31A-8]
    read_out: R31A-0
    read_in: R31A-1
  - mux: 10
    ctrl: [U14A-5, U14A-6, U14A-7, U14A-8]
    read_out: U14A-0
    read_in: U14A-1
  - mux: 11
    ctrl: [U7B-7, U7B-11, U7B-13, U7B-8]
    read_out: R31A-13
    read_in: R31A-12
  - mux: 12
    ctrl: [U13B-5, U13B-0, U13B-2, U13B-6]
    read_out: Q73A-8
    read_in: Q73A-7
  - mux: 13
    ctrl: [Q73A-2, Q73A-4, Q73A-9, Q73A-11]
    read_out: Q73A-1
    read_in: Q73A-0
  - mux: 14
    ctrl: [U13B-7, U13B-11, U13B-13, U13B-8]
    read_out: R23A-0
    read_in: R23A-1
