"""Compatibility exports for shared Plotly figure factory helpers."""

from __future__ import annotations

from qxvisualizer.figure_factory import (
    DEFAULT_HEIGHT,
    DEFAULT_TEMPLATE,
    DEFAULT_WIDTH,
    FIGURE_SIZE_IQ,
    FIGURE_SIZE_STANDARD,
    FIGURE_SIZE_TALL,
    IQ_AXIS_MARGIN_LEFT,
    IQ_AXIS_MARGIN_RIGHT,
    MEASUREMENT_SCHEDULE_BASE_HEIGHT,
    MEASUREMENT_SCHEDULE_DEFAULT_WIDTH,
    MEASUREMENT_SCHEDULE_ROW_HEIGHT,
    SEQUENCER_TIMELINE_BASE_HEIGHT,
    SEQUENCER_TIMELINE_DEFAULT_WIDTH,
    SEQUENCER_TIMELINE_LANE_HEIGHT,
    SEQUENCER_TIMELINE_MIN_HEIGHT,
    FigureSize,
    make_figure,
    show_figure,
)

__all__ = [
    "DEFAULT_HEIGHT",
    "DEFAULT_TEMPLATE",
    "DEFAULT_WIDTH",
    "FIGURE_SIZE_IQ",
    "FIGURE_SIZE_STANDARD",
    "FIGURE_SIZE_TALL",
    "IQ_AXIS_MARGIN_LEFT",
    "IQ_AXIS_MARGIN_RIGHT",
    "MEASUREMENT_SCHEDULE_BASE_HEIGHT",
    "MEASUREMENT_SCHEDULE_DEFAULT_WIDTH",
    "MEASUREMENT_SCHEDULE_ROW_HEIGHT",
    "SEQUENCER_TIMELINE_BASE_HEIGHT",
    "SEQUENCER_TIMELINE_DEFAULT_WIDTH",
    "SEQUENCER_TIMELINE_LANE_HEIGHT",
    "SEQUENCER_TIMELINE_MIN_HEIGHT",
    "FigureSize",
    "make_figure",
    "show_figure",
]
