# Example box catalog shared by the system examples.
#
# Format
# ------
# <box_id>:
#   name: <box_name>
#   type: <box_type>
#   address: <ip_address>  # required for QuBE and QuEL-1
#   adapter: <adapter_id>  # required for QuBE and QuEL-1
#   options: [<option_label>, ...]  # optional backend-specific box options

Q2A:
  name: "QuBE OU #1-02"
  type: "quel1-a"
  address: "10.1.0.2"
  adapter: "500202A504YAA"
U7B:
  name: "QuBE OU #2-03"
  type: "qube-riken-a"
  address: "10.1.0.7"
  adapter: "500202A504AAA"
U10B:
  name: "QuBE OU #2-06"
  type: "qube-ou-b"
  address: "10.1.0.10"
  adapter: "500202A503YAA"
U11A:
  name: "QuBE OU #2-"
  type: "qube-ou-a"
  address: "10.1.0.11"
  adapter: ""
U13B:
  name: "QuBE OU #2-09"
  type: "qube-ou-b"
  address: "10.1.0.13"
  adapter: "500202A507XAA"
U14A:
  name: "QuBE OU #2-10"
  type: "qube-ou-a"
  address: "10.1.0.14"
  adapter: "500202A502YAA"
U15A:
  name: "QuBE OU #2-11"
  type: "qube-ou-a"
  address: "10.1.0.15"
  adapter: "500202A501OAA"
R19A:
  name: "QuBE Riken #1-01"
  type: "qube-riken-a"
  address: "10.1.0.19"
  adapter: "500202A502CAA"
R20A:
  name: "QuBE Riken #1-02"
  type: "qube-riken-a"
  address: "10.1.0.20"
  adapter: "500202A500IAA"
R21B:
  name: "QuBE Riken #1-03"
  type: "qube-riken-b"
  address: "10.1.0.21"
  adapter: "500202A501DAA"
R23A:
  name: "QuBE Riken #1-05"
  type: "qube-riken-a"
  address: "10.1.0.23"
  adapter: "500202A509IAA"
R25A:
  name: "QuBE Riken #1-07"
  type: "qube-riken-a"
  address: "10.1.0.25"
  adapter: "500202A501QAA"
R26A:
  name: "QuBE Riken #1-08"
  type: "qube-riken-a"
  address: "10.1.0.26"
  adapter: "500202A503EAA"
R28A:
  name: "QuBE Riken #1-10"
  type: "qube-riken-a"
  address: "10.1.0.28"
  adapter: "500202A504RAA"
R31A:
  name: "QuBE OU #3-01"
  type: "qube-riken-a"
  address: "10.1.0.31"
  adapter: "500202A505PAA"
Q73A:
  name: "QuEL-1 #5-01"
  type: "quel1-a"
  address: "10.1.0.73"
  adapter: "500202A50TAAA"
S159A:
  name: "QuEL-1 SE (7-11GHz)"
  type: "quel1se-fujitsu11-a"
  address: "10.1.0.159"
  adapter: "500202A800QAA"
S160R:
  name: "QuEL-1 SE R8 #1"
  type: "quel1se-riken8"
  address: "10.1.0.160"
  adapter: "500202A800RAA"
  options:
    - "se8_mxfe1_awg2222"
QT1:
  name: "quel3-02-a01"
  type: "quel3"
QT2:
  name: "quel3-02-a02"
  type: "quel3"
QT3:
  name: "quel3-02-a03"
  type: "quel3"
QT4:
  name: "quel3-02-a04"
  type: "quel3"
QT5:
  name: "quel3-02-a05"
  type: "quel3"
QT6:
  name: "quel3-02-a06"
  type: "quel3"
QT7:
  name: "quel3-02-a07"
  type: "quel3"
QT8:
  name: "quel3-02-a08"
  type: "quel3"
